# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ffe45e0d15e8e32382c49db5f8935fa201d107e3fd567ad7f0f22be34828c0f3a7486330f417ece177befa86ec613ed94a505420f82301365a9f1206e0bf2f6

test:
  secret_key_base: f6dbbc143d960312771b3ae6e9a99afc66d58f8bf3762ca81a2f34997daafe985a00787bb8ff9cda607b9b0251a08909c67492c1c8b8d44ae0cd42c0f3d1dfe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
